version: '3.8'

services:
  qdrant:
    image: qdrant/qdrant:latest
    container_name: workit_qdrant
    restart: always
    ports:
      - "${QDRANT_PORT}:6333"
      - "${QDRANT_GRPC_PORT}:6334"
    volumes:
      - ./docker/qdrant_storage:/qdrant/storage
    networks:
      - workit_network

networks:
  workit_network:
    driver: bridge