# Generated by Django 6.0.5 on 2026-07-08 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_rfpparseddata"),
    ]

    operations = [
        migrations.AddField(
            model_name="rfpparseddata",
            name="qa_report",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="QA 검수 리포트"
            ),
        ),
    ]
