# Generated by Django 6.0.5 on 2026-07-07 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0003_rfpparseddata"),
        ("performance", "0004_techapplycheckresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="FinalReportParsedData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("parsed_json", models.JSONField(blank=True, default=dict)),
                (
                    "qa_report",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="QA 검수 리포트"
                    ),
                ),
                (
                    "parse_status",
                    models.CharField(
                        choices=[
                            ("pending", "대기"),
                            ("processing", "처리중"),
                            ("done", "완료"),
                            ("failed", "실패"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("parsed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "deliverable",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="final_parsed_data",
                        to="performance.deliverable",
                    ),
                ),
            ],
            options={
                "verbose_name": "사업추진결과보고서 파싱 결과",
                "verbose_name_plural": "사업추진결과보고서 파싱 결과 목록",
            },
        ),
        migrations.CreateModel(
            name="RFPFinalComparisonResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comparison_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "final_report_parsed",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="performance.finalreportparseddata",
                    ),
                ),
                (
                    "performance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rfp_final_comparisons",
                        to="performance.performance",
                    ),
                ),
                (
                    "rfp_parsed",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="contracts.rfpparseddata",
                    ),
                ),
            ],
            options={
                "verbose_name": "RFP ↔ 결과보고서 비교 결과",
                "verbose_name_plural": "RFP ↔ 결과보고서 비교 결과 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
