# Generated by Django 6.0.5 on 2026-07-07 06:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0005_finalreportparseddata_rfpfinalcomparisonresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="PEPFinalComparisonResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("comparison_json", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "execution_plan_parsed",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="performance.executionplanparseddata",
                    ),
                ),
                (
                    "final_report_parsed",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="performance.finalreportparseddata",
                    ),
                ),
                (
                    "performance",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pep_final_comparisons",
                        to="performance.performance",
                    ),
                ),
            ],
            options={
                "verbose_name": "사업수행계획서 ↔ 결과보고서 비교 결과",
                "verbose_name_plural": "사업수행계획서 ↔ 결과보고서 비교 결과 목록",
                "ordering": ["-created_at"],
            },
        ),
        migrations.DeleteModel(
            name="RFPFinalComparisonResult",
        ),
    ]
