# Generated by Django 6.0.5 on 2026-07-07 08:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0006_pepfinalcomparisonresult_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AIAnalysisLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("analysis_ok", "분석 완료 - 이슈 없음"),
                            ("analysis_issue", "분석 완료 - 이슈 발견"),
                            ("proceed_no_issue", "이슈 없이 다음 단계 진행"),
                            ("proceed_with_issue", "이슈 있었지만 반려 없이 진행"),
                            ("reject", "반려 (다시 업로드)"),
                        ],
                        max_length=30,
                        verbose_name="이벤트 유형",
                    ),
                ),
                (
                    "issue_count",
                    models.IntegerField(default=0, verbose_name="이슈 건수"),
                ),
                (
                    "detail",
                    models.JSONField(blank=True, default=dict, verbose_name="상세"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="발생 시각"),
                ),
                (
                    "deliverable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ai_analysis_logs",
                        to="performance.deliverable",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 분석 로그",
                "verbose_name_plural": "AI 분석 로그 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
