# Generated by Django 6.0.5 on 2026-07-13 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0007_aianalysislog"),
    ]

    operations = [
        migrations.AddField(
            model_name="pepfinalcomparisonresult",
            name="started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="분석 시작 시각"
            ),
        ),
        migrations.AddField(
            model_name="pepfinalcomparisonresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("idle", "대기"),
                    ("processing", "분석중"),
                    ("done", "완료"),
                    ("failed", "실패"),
                ],
                default="idle",
                max_length=20,
                verbose_name="분석 상태",
            ),
        ),
        migrations.AddField(
            model_name="pepfinalcomparisonresult",
            name="task_id",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Celery task id"
            ),
        ),
        migrations.AddField(
            model_name="rfpcomparisonresult",
            name="started_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="분석 시작 시각"
            ),
        ),
        migrations.AddField(
            model_name="rfpcomparisonresult",
            name="status",
            field=models.CharField(
                choices=[
                    ("idle", "대기"),
                    ("processing", "분석중"),
                    ("done", "완료"),
                    ("failed", "실패"),
                ],
                default="idle",
                max_length=20,
                verbose_name="분석 상태",
            ),
        ),
        migrations.AddField(
            model_name="rfpcomparisonresult",
            name="task_id",
            field=models.CharField(
                blank=True, default="", max_length=255, verbose_name="Celery task id"
            ),
        ),
    ]
