# Generated by Django 6.0.5 on 2026-07-14 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contracts", "0006_backfill_aireviewresult_status"),
        ("performance", "0008_pepfinalcomparisonresult_started_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AIPerfLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feature",
                    models.CharField(
                        choices=[
                            ("contract_review", "계약서 AI분석"),
                            ("kickoff_analyze", "과업수행계획서 AI분석"),
                            ("tech_apply_check", "기술적용결과표 검토"),
                            ("final_analyze", "사업추진결과보고서 AI분석"),
                        ],
                        max_length=30,
                        verbose_name="기능",
                    ),
                ),
                ("started_at", models.DateTimeField(verbose_name="시작 시각")),
                ("finished_at", models.DateTimeField(verbose_name="종료 시각")),
                ("duration_seconds", models.FloatField(verbose_name="소요 시간(초)")),
                (
                    "success",
                    models.BooleanField(default=True, verbose_name="성공 여부"),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="부가 정보"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contract_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contracts.contractdocument",
                    ),
                ),
                (
                    "deliverable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="performance.deliverable",
                    ),
                ),
                (
                    "performance",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="performance.performance",
                    ),
                ),
            ],
            options={
                "verbose_name": "AI 처리 성능 로그",
                "verbose_name_plural": "AI 처리 성능 로그 목록",
                "ordering": ["-created_at"],
            },
        ),
    ]
