# Generated by Django 6.0.5 on 2026-07-16 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("performance", "0009_aiperflog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverable",
            name="deliverable_type",
            field=models.CharField(
                choices=[
                    ("kickoff", "과업수행계획서"),
                    ("tech_apply", "기술적용결과표"),
                    ("final", "사업추진결과보고서"),
                ],
                max_length=20,
                verbose_name="산출물 유형",
            ),
        ),
    ]
